name: Azure PowerShell CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Azure PowerShell
      run: |
        Install-Module -Name Az -Force -Scope CurrentUser
        Import-Module Az
      shell: pwsh

    - name: Run CreateVM script
      run: ./CreateVM.ps1
      shell: pwsh
