name: PowerShell CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PowerShell
        uses: PowerShell/setup-powershell@v1

      - name: Run PowerShell Script
        run: pwsh ./create-vm.ps1
